spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/estabelecimento
    username: postgres
    password: 1234
  mvc:
    static-path-pattern: /swagger*

springdoc:
  swagger-ui.path: /swagger-ui.html